#!/bin/bash
set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

printf "${GREEN}*** Cleaning up all containers ***${NC}\n"
docker-compose -f docker-compose.yml down -v || {
	# this block will run if ```docker-compose down -v``` fails.
	sleep 3

	printf "${GREEN}*** Remove nightfall network ***${NC}\n"
  docker network rm nightfall_network

  printf "${GREEN}*** Remove nightfall's mongo volume ***${NC}\n"
  docker volume rm nightfall_mongo-nightfall-volume

  printf "${GREEN}*** Remove zkp-code volume ***${NC}\n"
  docker volume rm nightfall_zkp-code-volume

	printf "${GREEN}*** Remove merkle_tree network ***${NC}\n"
  docker network rm merkle_tree_network

	printf "${GREEN}*** Remove the merkle tree's mongo volume ***${NC}\n"
  docker volume rm nightfall_mongo-merkle-tree-volume
}

printf "${GREEN}*** Pull zokrates docker image ***${NC}\n"
#docker pull zokrates/zokrates:0.5.1

printf "${GREEN}*** Installing zkp-util dependencies"
#pushd zkp-utils
#npm ci
#popd

printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
#docker-compose up -d ganache
docker-compose up -d custom-geth

printf "${GREEN}*** Deploying all contracts ***${NC}\n"

docker-compose run --rm truffle-offchain migrate --reset --network=default
docker-compose run --rm truffle-zkp migrate --reset --network=default

printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
docker-compose -f docker-compose.yml up --build
