#!/bin/bash
set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

printf "${GREEN}*** Cleaning up all containers ***${NC}\n"
docker-compose down -v || true

printf "${GREEN}*** Pull zokrates docker image ***${NC}\n"
docker pull michaelconnor/zok:2Jan2019

printf "${GREEN}*** Installing zkp-util dependencies"
pushd zkp-utils
npm install
popd

printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
docker-compose up -d ganache

printf "${GREEN}*** Deploying all contracts ***${NC}\n"
make truffle-migrate

printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
docker-compose up -d

printf "${GREEN}*** Tailing Logs ***${NC}\n"
docker-compose logs -f
