#!/bin/bash
set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

printf "${GREEN}*** Cleaning up all containers ***${NC}\n"
docker-compose down -v || {
	# this block will run if ```docker-compose down -v``` fails.
	sleep 3

	printf "${GREEN}*** Remove network ***${NC}\n"
	docker network rm nightfall_default

	printf "${GREEN}*** Remove mongo volume ***${NC}\n"
	docker volume rm nightfall_mongo-volume

	printf "${GREEN}*** Remove zkp-code volume ***${NC}\n"
	docker volume rm nightfall_zkp-code
}

printf "${GREEN}*** Pull zokrates docker image ***${NC}\n"
docker pull michaelconnor/zok:2Jan2019

printf "${GREEN}*** Installing zkp-util dependencies"
pushd zkp-utils
npm install
popd

printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
docker-compose up -d ganache

printf "${GREEN}*** Deploying all contracts ***${NC}\n"
make truffle-migrate

printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
docker-compose up -d

printf "${GREEN}*** Tailing Logs ***${NC}\n"
docker-compose logs -f
